version: 2

sources:
  - name: source_name_airbnb
    database: airbnb  
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
      
      - name: hosts
        identifier: raw_hosts

      - name: HOSTS_stream
        identifier: RAW_HOSTS_stream

      - name: reviews
        identifier: raw_reviews

  - name: source_jaffle_shop
    database: airbnb
    schema: jaffle_shop
    tables:
      - name: customers
        identifier: customers

      - name: orders
        loaded_at_field: _etl_loaded_at
        freshness: # default freshness
          warn_after: {count: 12, period: hour}
          error_after: {count: 12, period: hour}

  - name: source_stripe
    database: airbnb  
    schema: stripe
    tables:
      - name: payment
        identifier: payment
